# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'Ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build --if-present
  displayName: 'Install dependencies'

- script: |
    npm install mocha chai --save-dev
    echo "const chai = require('chai'); const expect = chai.expect; describe('Dummy Test', () => { it('should pass', () => { expect(true).to.equal(true); }); });" > test.js
    npx mocha test.js
  displayName: 'Run tests'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription'
    appName: 'jagruti-cicd-demo-app'
    package: '$(System.DefaultWorkingDirectory)'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
